# set the time - VMWARE fs up a lot

# rvm
export PATH=/var/lib/gems/1.8/bin:$PATH
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

# gemsets and put it in the prompt ala https://rvm.beginrescueend.com/workflow/prompt/
PS1="\$(~/.rvm/bin/rvm-prompt g)|$PS1"

# my execs are in bin
export PATH=~/workspace/bin:$PATH

# common mistakes i make
alias cd..='cd ..'
alias ks='ls'
alias cls='clear'

# vi luvs
# alias vi='gvim'
alias vim='gvim'
